# Generated by Django 4.0.4 on 2022-10-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='emotion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='state',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
