# Generated by Django 4.1.2 on 2022-11-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_state_emotion_alter_state_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='humans',
            field=models.IntegerField(default=0),
        ),
    ]
