# Generated by Django 4.1.2 on 2022-11-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_state_humans'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='slave',
            field=models.IntegerField(default=0),
        ),
    ]
